### ISSUE TITLE
Preloader Functionality

### ISSUE THREAD

**Issue by DhairyaBahl** [hash-define-organization/Hash-Whiteboard#17]
### Description
Add loading screen before the rendering of the application where it should show some decent animation with Hash Define written on it along with its logo.

You can use Lazy and suspense from react-router-dom to achieve this functionality.

**Comment by shreya024** [comment]
I would like to work on this issue.Kindly assign @DhairyaBahl

**Comment by DhairyaBahl** [comment]
@shreya024 Assigned ! Looking forward to a PR.
