### ISSUE TITLE
Change title and add a new favicon

### ISSUE THREAD

**Issue by VaibhavUpreti** [hash-define-organization/Hash-Whiteboard#18]
I think we need should change the title of the whiteboard from "React App" to " Hash Board" (my personal suggestion feel free to shoot yours). Also the basic react icon looks a bit odd. We can create a custom one.

I am interested and would like to work on this issue :)

**Comment by VaibhavUpreti** [comment]
Under GSSOC'22 as a contributor

**Comment by VaibhavUpreti** [comment]
![favicon-32x32](https://user-images.githubusercontent.com/85568177/156371800-09c57374-b9c9-4cda-ad13-24c8b466d488.png)

how does this look for a favicon?

**Comment by vedant-jain03** [comment]
@VaibhavUpreti Favicon is under review you can definitely change the name. Go ahead!

**Comment by VaibhavUpreti** [comment]
Hey, I need some help with this issue. I cannot find how to change the name of the title. Should I add the document.title using reactdom or is there any other way. Can any of the mentors pls guide me

**Comment by DhairyaBahl** [comment]
> ![favicon-32x32](https://user-images.githubusercontent.com/85568177/156371800-09c57374-b9c9-4cda-ad13-24c8b466d488.png)
> 
> how does this look for a favicon?

I suggest you do use something similar to our hash define colors. Do check those out. There is also a banner in Reacme.md. I was expecting similar colors.

**Comment by Olaleye-Blessing** [comment]
> Hey, I need some help with this issue. I cannot find how to change the name of the title. Should I add the document.title using reactdom or is there any other way. Can any of the mentors pls guide me

@VaibhavUpreti follow this step to change the title:

- go into public folder
- go into index.html
- look for the title tag
- clear the 'React App' and change it to the title you want to use

Hope this helps

**Comment by VaibhavUpreti** [comment]
Thank you @Olaleye-Blessing this was really helpful!!!
