### ISSUE TITLE
Add yarn usage in readme

### ISSUE THREAD

**Issue by VaibhavUpreti** [hash-define-organization/Hash-Whiteboard#21]
I think we should also add in the readme file a guide on how folks can run the various scripts of the projects using "yarn" namely
1. build
2. start
3. test

This also means we need to include a yarn.lock file in the codebase.

I have already added this feature in my personal codebase as a participant in GSSOC'22. It looks something like this-

![Screenshot 2022-03-02 at 7 46 42 PM](https://user-images.githubusercontent.com/85568177/156378890-a8b86f98-e502-4bc3-9089-300469b84e0f.png)

Waiting for the mentor to assign me the issue and subsequently create the pull request

**Comment by DhairyaBahl** [comment]
Assigned ! Looking forward to a PR from your side !!
