### ISSUE TITLE
Pen thickness Pop Up panel when pen is clicked

### ISSUE THREAD

**Issue by arzitmahajan** [hash-define-organization/Hash-Whiteboard#26]

**Comment by DhairyaBahl** [comment]
@arzitmahajan Would you like to work on this ?

**Comment by arzitmahajan** [comment]
Yes I would

**Comment by vedant-jain03** [comment]
@arzitmahajan Kindly provide some valid description and you can start working on the implementation.

**Comment by arzitmahajan** [comment]
First I will make panel whenever then pen tool is clicked and that panel will contain slide bar so that user can adjust pen's thickness. After doing so I will work on the main part that is whenever slide bar is used pen's thickness actually changes
