### ISSUE TITLE
Feature: Eraser Thickness Pop-Up

### ISSUE THREAD

**Issue by DhairyaBahl** [hash-define-organization/Hash-Whiteboard#27]
### Description
When user clicks on the Eraser Icon, then a pop-up must come in the right of the eraser icon with multiple thickness options.

**Comment by varun14gb** [comment]
I would like to work on this issue.
Kindly Assign.

**Comment by vedant-jain03** [comment]
@varun14gb Go Ahead

**Comment by varun14gb** [comment]
@vedant-jain03 I have made PR #30 
Kindly check and if everything is being alright merge it. Thank You.
