### ISSUE TITLE
Add Key-Binding for Icons

### ISSUE THREAD

**Issue by Shubham29012001** [hash-define-organization/Hash-Whiteboard#50]
It would be great if key-binding would be applied to icons so that users don't need to click every time on the icon instead they can just press the command keys. It would help to enhance the user experience. E.g - To undo any operation on the site, users still need to click on the Undo icons but by keybinding, they can directly use CTRL+Z to undo the operation.

I would like to work on this issue for GSSoC '22. Please assign it to me.

**Comment by vedant-jain03** [comment]
@Shubham29012001 Great Idea
