### ISSUE TITLE
Fill color in whiteboard

### ISSUE THREAD

**Issue by vasantisuthar** [hash-define-organization/Hash-Whiteboard#51]
It is good if we can add a fill color element to fill the color in the shapes or background.

If this needs to be added I want to work on it.
Please assign these to me.

**Comment by vedant-jain03** [comment]
@vasantisuthar Thankyou for your interest but the PR for similar issue is under review https://github.com/hash-define-organization/Hash-Whiteboard/pull/22

Please checkout another issue or create a new one if you find it!
