### ISSUE TITLE
Update Readme with some important points

### ISSUE THREAD

**Issue by DhairyaBahl** [hash-define-organization/Hash-Whiteboard#9]
@vedant-jain03 Kindly lead this issue. You can assign this to other contributors if needed but this is the top priority and must be done asap.

Add the following points in the Github Readme:

* Writing a blog about your contribution is a must after getting your PR merged! Otherwise, maintainers have right to revert the PR.
* Make sure to fork the repository and run the code in your local environment, then only you will get assigned to an issue.

Edit the Contributing guideline for Girls-script summer of codes by adding descriptions about labels we have
- GSSoC'22
- Level-1
- Level-2
- Level-3

**Comment by vedant-jain03** [comment]
@Aniruddha-Inge have a loot at updated description.

**Comment by Aniruddha-Inge** [comment]
> @Aniruddha-Inge have a loot at updated description.

updated description of labels?

**Comment by Aniruddha-Inge** [comment]
@vedant-jain03 please let me know where in Readme should I add the above two points, and in the contributing guideline, should I create a new section named GSSOC 2022 in which I can mention the information about the labels too?

**Comment by Aniruddha-Inge** [comment]
@vedant-jain03 Please have a look at #41 and let me know what more changes can be done.
